package com.marketing.Repository.dbaquamovil;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.marketing.Model.dbaquamovil.TblDctos;
import com.marketing.Projection.ReporteFeDTO;
import com.marketing.Projection.TblDctosDTO;
import com.marketing.Projection.TblDctosDTO2;

@Repository
public interface TblDctosRepo extends JpaRepository<TblDctos, Integer> {

	@Query("SELECT MAX(r.idDcto) FROM TblDctos r " +
			  "WHERE r.IDLOCAL = ?1 " +
			  "AND r.IDTIPOORDEN = 17 ")
	    Integer findMaxIdDcto(int IDLOCAL);
	
	  @Query(value = "SELECT idDcto " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.IDORDEN = ?2 " +
              "AND tblDctos.idCliente = ?3 ",
              nativeQuery = true)
	  Integer ObtenerIdDcto(int idLocal, int IDORDEN, String idCliente);
	  
	  @Query(value = "SELECT fechaDcto " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.IDORDEN = ?2 " +
              "AND tblDctos.idCliente = ?3 ",
              nativeQuery = true)
	  String ObtenerFechaDcto(int idLocal, int IDORDEN, String idCliente);
	  
	  @Query(value = "SELECT DISTINCT idCliente " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.IDTIPOORDEN = 17 ",
              nativeQuery = true)
	  List<String> ObtenerClientesPQR(int idLocal);
	  
	  @Query(value = "SELECT  idDcto " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.idCliente = ?2 "+
              "AND tblDctos.IDTIPOORDEN = 17 ",
              nativeQuery = true)
	  List<Integer> ObtenerListaPQR(int idLocal, String idCliente);
	  
	  @Query(value = "SELECT  IDORDEN " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.idDcto = ?2 " +
              "AND tblDctos.IDTIPOORDEN = 17 ",
              nativeQuery = true)
	  Integer ObtenerIDORDEN(int idLocal, int idDcto);
	  
	  @Query(value = "SELECT  IDORDEN " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.idDcto IN ?2 "+
              "AND tblDctos.IDTIPOORDEN = 17 ",
              nativeQuery = true)
	  List<Integer> ObtenerListaIDORDEN(int idLocal, List<Integer> idDcto);
	  
	  @Query(value = "SELECT  IDORDEN " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.IDTIPOORDEN = ?2 " +
              "AND tblDctos.idPeriodo = ?3",
              nativeQuery = true)
	  List<Integer> ObtenerCantidadFacturas(int idLocal, int idTipoOrden, int idPeriodo );
	  
	  @Query(value = "SELECT  envioFE, COUNT(*) AS cuenta " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.IDTIPOORDEN = ?2 " +
              "AND tblDctos.idPeriodo = ?3 " +
              "group by envioFE ",
              nativeQuery = true)
	  List<ReporteFeDTO> ObtenerReporteFE(int idLocal, int idTipoOrden, int idPeriodo );
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = "DELETE FROM tbldctos " +
	                 "WHERE tbldctos.IDLOCAL = ?1 " +
	                 "AND tbldctos.IDTIPOORDEN   IN (7,9,29, 59) " +
	                 "AND tbldctos.idPeriodo =  ?2 ", nativeQuery = true)
	  public void retiraDctos(int idLocal, int idPeriodo);
	  
	  
	  
	  
	  @Query(value = " SELECT tblDctos.idLocal,             "                 
			  + "   tblDctos.idTipoOrden,                   "
			  + "   tblDctos.idDcto,                        "
			  + "   tblDctos.idOrden,                       "
			  + "   tblDctos.fechaDcto,                     "
			  + "   tblDctos.indicador,                     "
			  + "   tblDctos.idCliente,                     "
			  + "   tblDctos.vrBase,                        "
			  + "   tblDctos.vrIva,                         "
			  + "   tblDctos.vrCostoMV,                     "
			  + "   tblDctos.nombreTercero,                 "
			  + "   tblDctos.idDctoNitCC,                   "
			  + "   tblDctos.fechaDctoNitCC,                "
			  + "   tblDctos.idLocalCruce,                  "
			  + "   tblDctos.idTipoOrdenCruce,              "
			  + "   tblDctos.idDctoCruce,                   "
			  + "   (tblDctos.vrBase      +                 "
			  + "   tblDctos.vrIva       -                  "
			  + "   tblDctos.vrRteFuente -                  "
			  + "   tblDctos.vrRteIva) AS vrFactura,        "
			  + "   tblDctos.vrDescuento,                   "
			  + "   tblDctos.vrRteFuente,                   "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoOrden = 1          "
			  + "   THEN    tblDctos.idDctoNitCC            "
			  + "   ELSE    STR(tblDctos.idDcto)            "
			  + "   END) AS idDctoStr,                      "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoNegocio = 1        "
			  + "   THEN      'CONTADO'                     "
			  + "   ELSE      'CREDITO'                     "
			  + "   END) AS nombreTipoNegocio,              "
			  + "   tblDctos.idTipoNegocio,                 "
			  + "   ctrlUsuarios.aliasUsuario,              "
			  + "   tblTercerosRuta.nombreRuta,             "
			  + "   tblTerceroEstracto.nombreEstracto       "
			  + "                    AS nombreEstrato,      "
			  + "   tblDctosOrdenes.OBSERVACION,            "   
			  + "   tblTerceros.CC_Nit,                     "
			  + "   tblDctosPeriodo.fechaConRecargo         "
			  + "                            AS fechaVcto   "
			  + "   FROM   tblDctos                         "     
			  + "   INNER JOIN tblDctosOrdenes              "    
			  + "   ON tblDctosOrdenes.IDLOCAL              "
			  + "                    =tblDctos.IDLOCAL      "
			  + "   AND tblDctosOrdenes.IDTIPOORDEN =       "    
			  + "                tblDctos.IDTIPOORDEN       "
			  + "   AND tblDctosOrdenes.IDORDEN   =         "      
			  + "                  tblDctos.IDORDEN         "
			  + "   INNER JOIN tblTerceros                  "    
			  + "   ON tblTerceros.idLocal        =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND tblTerceros.idCliente     =         "        
			  + "                tblDctos.idCliente         "
			  + "   INNER JOIN tblDctosPeriodo              "
			  + "   ON tblDctosPeriodo.idLocal    =         "
			  + "                  tblDctos.idLocal         "
			  + "   AND tblDctosPeriodo.idPeriodo =         "
			  + "                tblDctos.idPeriodo         "
			  + "   INNER JOIN ctrlUsuarios                 "
			  + "   ON ctrlUsuarios.idLocal       =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND ctrlUsuarios.idUsuario    =         "
			  + "               tblDctos.idVendedor         "
			  + "   INNER JOIN tblTercerosRuta              "
			  + "   ON tblTercerosRuta.idLocal    =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTercerosRuta.idRuta    =         "
			  + "                tblTerceros.idRuta         "
			  + "   INNER JOIN tblTerceroEstracto           "
			  + "   ON tblTerceroEstracto.idLocal =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTerceroEstracto.idEstracto =     "
			  + "               tblTerceros.idEstracto      "
			  + "                  WHERE EXISTS             "                    
			  + "  ( SELECT *                               " 
			  + "    FROM   tblDctosOrdenes                 " 
			  + "    INNER JOIN tblDctosOrdenesDetalle      " 
			  + "    ON tblDctosOrdenes.IDLOCAL      =      " 
			  + "       tblDctosOrdenesDetalle.IDLOCAL      " 
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "   tblDctosOrdenesDetalle.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "       tblDctosOrdenesDetalle.IDORDEN      " 
			  + "    WHERE tblDctosOrdenes.IDLOCAL   =      " 
			  + "                     tblDctos.IDLOCAL      "
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "                 tblDctos.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "          tblDctos.IDORDEN)                "
			  + "    AND tblDctos.idLocal   =               " 
			  + "?1                              "                
			  + "    AND tblDctos.idPeriodo =               "  
			  + "?2                           "                       
			  + " AND tblDctos.idTipoOrden  IN             ("
			  + "?3 ,                    "
			  + "?4 )                    "  
			  + " AND tblDctos.indicador BETWEEN            "
			  + "?5      AND          "
			  + "?6                      " 
			  + " AND    tblTercerosRuta.idRuta =              "
			  + "?7                                 "                
			  + "    AND tblTerceros.IDTIPOTERCERO =1       "			 
			  + "    ORDER BY tblDctos.fechaDcto,           "      
			  + "             tblDctos.idTipoOrden,         "      
			  + "             tblDctos.idDcto",
              nativeQuery = true)
	  List<TblDctosDTO> listaRepNotaRuta(int idLocal, int idPeriodo, int IdTipoOrdenINI, int IdTipoOrdenFIN, int IndicadorINICIAL, int IndicadorFINNAL, int idRuta );
	  
	  
	  

	  @Query(value = " SELECT tblDctos.idLocal,                    "             
			  + "   tblDctos.idTipoOrden,                   "
			  + "   tblDctos.idDcto,                        "
			  + "   tblDctos.idOrden,                       "
			  + "   tblDctos.fechaDcto,                     "
			  + "   tblDctos.indicador,                     "
			  + "   tblDctos.idCliente,                     "
			  + "   tblDctos.vrBase,                        "
			  + "   tblDctos.vrIva,                         "
			  + "   tblDctos.vrCostoMV,                     "
			  + "   tblDctos.nombreTercero,                 "
			  + "   tblDctos.idDctoNitCC,                   "
			  + "   tblDctos.fechaDctoNitCC,                "
			  + "   tblDctos.idLocalCruce,                  "
			  + "   tblDctos.idTipoOrdenCruce,              "
			  + "   tblDctos.idDctoCruce,                   "
			  + "   (tblDctos.vrBase      +                 "
			  + "   tblDctos.vrIva       -                  "
			  + "   tblDctos.vrRteFuente -                  "
			  + "   tblDctos.vrRteIva) AS vrFactura,        "
			  + "   tblDctos.vrDescuento,                   "
			  + "   tblDctos.vrRteFuente,                   "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoOrden = 1          "
			  + "   THEN    tblDctos.idDctoNitCC            "
			  + "   ELSE    STR(tblDctos.idDcto)            "
			  + "   END) AS idDctoStr,                      "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoNegocio = 1        "
			  + "   THEN      'CONTADO'                     "
			  + "   ELSE      'CREDITO'                     "
			  + "   END) AS nombreTipoNegocio,              "
			  + "   tblDctos.idTipoNegocio,                 "
			  + "   ctrlUsuarios.aliasUsuario,              "
			  + "   tblTercerosRuta.nombreRuta,             "
			  + "   tblTerceroEstracto.nombreEstracto       "
			  + "                    AS nombreEstrato,      "
			  + "   tblDctosOrdenes.OBSERVACION,            "   
			  + "   tblTerceros.CC_Nit,                     "
			  + "   tblDctosPeriodo.fechaConRecargo         "
			  + "                            AS fechaVcto   "
			  + "   FROM   tblDctos                         "     
			  + "   INNER JOIN tblDctosOrdenes              "    
			  + "   ON tblDctosOrdenes.IDLOCAL              "
			  + "                    =tblDctos.IDLOCAL      "
			  + "   AND tblDctosOrdenes.IDTIPOORDEN =       "    
			  + "                tblDctos.IDTIPOORDEN       "
			  + "   AND tblDctosOrdenes.IDORDEN   =         "      
			  + "                  tblDctos.IDORDEN         "
			  + "   INNER JOIN tblTerceros                  "    
			  + "   ON tblTerceros.idLocal        =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND tblTerceros.idCliente     =         "        
			  + "                tblDctos.idCliente         "
			  + "   INNER JOIN tblDctosPeriodo              "
			  + "   ON tblDctosPeriodo.idLocal    =         "
			  + "                  tblDctos.idLocal         "
			  + "   AND tblDctosPeriodo.idPeriodo =         "
			  + "                tblDctos.idPeriodo         "
			  + "   INNER JOIN ctrlUsuarios                 "
			  + "   ON ctrlUsuarios.idLocal       =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND ctrlUsuarios.idUsuario    =         "
			  + "               tblDctos.idVendedor         "
			  + "   INNER JOIN tblTercerosRuta              "
			  + "   ON tblTercerosRuta.idLocal    =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTercerosRuta.idRuta    =         "
			  + "                tblTerceros.idRuta         "
			  + "   INNER JOIN tblTerceroEstracto           "
			  + "   ON tblTerceroEstracto.idLocal =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTerceroEstracto.idEstracto =     "
			  + "               tblTerceros.idEstracto      "
			  + "                  WHERE EXISTS             "                    
			  + "  ( SELECT *                               " 
			  + "    FROM   tblDctosOrdenes                 " 
			  + "    INNER JOIN tblDctosOrdenesDetalle      " 
			  + "    ON tblDctosOrdenes.IDLOCAL      =      " 
			  + "       tblDctosOrdenesDetalle.IDLOCAL      " 
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "   tblDctosOrdenesDetalle.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "       tblDctosOrdenesDetalle.IDORDEN      " 
			  + "    WHERE tblDctosOrdenes.IDLOCAL   =      " 
			  + "                     tblDctos.IDLOCAL      "
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "                 tblDctos.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "          tblDctos.IDORDEN)                "
			  + "    AND tblDctos.idLocal   =               " 
			  +" ?1                             "                
			  + "    AND tblDctos.idPeriodo =               "  
			  + "?2                           "                       
			  + " AND tblDctos.idTipoOrden  IN             ("
			  + "?3 ,                    "
			  + "?4 )                    "  
			  + " AND tblDctos.indicador BETWEEN            "
			  + "?5       AND          "
			  + "?6                     " 
			  + "    AND tblTerceros.IDTIPOTERCERO =1       "			 
			  + "    ORDER BY tblDctos.fechaDcto,           "      
			  + "             tblDctos.idTipoOrden,         "      
			  + "             tblDctos.idDcto",
              nativeQuery = true)
	  List<TblDctosDTO> listaRepNota(int idLocal, int idPeriodo, int IdTipoOrdenINI, int IdTipoOrdenFIN, int IndicadorINICIAL, int IndicadorFINNAL);
	  
	  
	  
	  
	  
	  @Query(value = "SELECT tblDctos.IDLOCAL,            "
              + "        IDTIPOORDEN,               "
              + " 	   IDORDEN,                   "
              + " 	   idDcto,                    "
              + " 	   tblDctos.idCliente,        "
              + " 	   tblTerceros.numeroMedidor, "
              + " 	   fechaDcto,                 "
              + " 	   GETDATE() AS fechaAbono,   "
              + " 	   vrBase,                    "
              + " 	   vrPago,                    "
              + "?1  AS vrAbono,         "
              + " 	    (vrBase - "
              + "?1 ) AS vrSaldo,         "
              + " 	   tblTerceros.nombreTercero, "
              + " 	   idPeriodo                  "
              + " FROM     tblDctos                 "
              + " INNER JOIN tblTerceros            "
              + " ON tblTerceros.idLocal            "
              + "                = tblDctos.IDLOCAL "
              + " AND tblTerceros.idCliente         "
              + "              = tblDctos.idCliente "
              + " WHERE tblDctos.IDLOCAL   =        "
              + "?2                    "
              + " AND IDTIPOORDEN          =        "
              + "?3                 "
              + " AND tblDctos.idCliente   =        "
              + "?4                  "
              + " AND tblDctos.idPeriodo   =        "
              + "?5 ",
              nativeQuery = true)
	  List<TblDctosDTO> listaDctoRepAbono(int ValorAbono, int idLocal, int xIdTipoOrden, String idCliente, int idPeriodo);
	  
	  
	  
	  @Query(value = "SELECT tblDctosOrdenesDetalle.IDPLU,             "
              + "       tblDctosOrdenesDetalle.NOMBREPLU,         "
              + "       tblDctosOrdenesDetalle.VRVENTAUNITARIO,   "
              + " 	  tblDctosOrdenesDetalle.idCliente,         "
              + " 	  tblTerceros.nombreTercero,                "
              + " 	  tblDctosOrdenes.idperiodo                 "
              + " FROM     tblDctosOrdenes                        "
              + " INNER JOIN tblDctosOrdenesDetalle               "
              + " ON tblDctosOrdenes.IDLOCAL      =               "
              + "                 tblDctosOrdenesDetalle.IDLOCAL  "
              + " AND tblDctosOrdenes.IDTIPOORDEN =               "
              + "             tblDctosOrdenesDetalle.IDTIPOORDEN  "
              + " AND tblDctosOrdenes.IDORDEN    =                "
              + "                 tblDctosOrdenesDetalle.IDORDEN  "
              + " INNER JOIN tblTerceros                          "
              + " ON tblTerceros.idLocal =                        "
              + "                 tblDctosOrdenesDetalle.IDLOCAL  "
              + " AND tblTerceros.idCliente =                     "
              + "               tblDctosOrdenesDetalle.idCliente  "
              + " WHERE tblDctosOrdenes.idLocal                =  "
              + "?1                                   "
              + " AND   tblDctosOrdenes.IDTIPOORDEN            =  "
              + "?2                              "
              + " AND tblDctosOrdenes.idPeriodo                =  "
              + "?3                                 "
              + " AND tblDctosOrdenesDetalle.IDTIPO NOT IN (4,6)  "
              + " AND tblDctosOrdenesDetalle.VRVENTAUNITARIO!=0   "
              + " ORDER BY tblDctosOrdenesDetalle.IDPLU,          "
              + "      tblTerceros.nombreTercero",
              nativeQuery = true)
	  List<TblDctosDTO> listaNovedad(int idLocal, int xIdTipoOrden, int idPeriodo);
	  
	  
	  @Query(value = " SELECT tblDctos.idLocal,                    "             
			  + "   tblDctos.idTipoOrden,                   "
			  + "   tblDctos.idDcto,                        "
			  + "   tblDctos.idOrden,                       "
			  + "   tblDctos.fechaDcto,                     "
			  + "   tblDctos.indicador,                     "
			  + "   tblDctos.idCliente,                     "
			  + "   tblDctos.vrBase,                        "
			  + "   tblDctos.vrIva,                         "
			  + "   tblDctos.vrCostoMV,                     "
			  + "   tblDctos.nombreTercero,                 "
			  + "   tblDctos.idDctoNitCC,                   "
			  + "   tblDctos.fechaDctoNitCC,                "
			  + "   tblDctos.idLocalCruce,                  "
			  + "   tblDctos.idTipoOrdenCruce,              "
			  + "   tblDctos.idDctoCruce,                   "
			  + "   (tblDctos.vrBase      +                 "
			  + "   tblDctos.vrIva       -                  "
			  + "   tblDctos.vrRteFuente -                  "
			  + "   tblDctos.vrRteIva) AS vrFactura,        "
			  + "   tblDctos.vrDescuento,                   "
			  + "   tblDctos.vrRteFuente,                   "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoOrden = 1          "
			  + "   THEN    tblDctos.idDctoNitCC            "
			  + "   ELSE    STR(tblDctos.idDcto)            "
			  + "   END) AS idDctoStr,                      "
			  + "   (CASE WHEN                              "
			  + "         tblDctos.idTipoNegocio = 1        "
			  + "   THEN      'CONTADO'                     "
			  + "   ELSE      'CREDITO'                     "
			  + "   END) AS nombreTipoNegocio,              "
			  + "   tblDctos.idTipoNegocio,                 "
			  + "   ctrlUsuarios.aliasUsuario,              "
			  + "   tblTercerosRuta.nombreRuta,             "
			  + "   tblTerceroEstracto.nombreEstracto       "
			  + "                    AS nombreEstrato,      "
			  + "   tblDctosOrdenes.OBSERVACION,            "   
			  + "   tblTerceros.CC_Nit,                     "
			  + "   tblDctosPeriodo.fechaConRecargo         "
			  + "                            AS fechaVcto   "
			  + "   FROM   tblDctos                         "     
			  + "   INNER JOIN tblDctosOrdenes              "    
			  + "   ON tblDctosOrdenes.IDLOCAL              "
			  + "                    =tblDctos.IDLOCAL      "
			  + "   AND tblDctosOrdenes.IDTIPOORDEN =       "    
			  + "                tblDctos.IDTIPOORDEN       "
			  + "   AND tblDctosOrdenes.IDORDEN   =         "      
			  + "                  tblDctos.IDORDEN         "
			  + "   INNER JOIN tblTerceros                  "    
			  + "   ON tblTerceros.idLocal        =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND tblTerceros.idCliente     =         "        
			  + "                tblDctos.idCliente         "
			  + "   INNER JOIN tblDctosPeriodo              "
			  + "   ON tblDctosPeriodo.idLocal    =         "
			  + "                  tblDctos.idLocal         "
			  + "   AND tblDctosPeriodo.idPeriodo =         "
			  + "                tblDctos.idPeriodo         "
			  + "   INNER JOIN ctrlUsuarios                 "
			  + "   ON ctrlUsuarios.idLocal       =         "
			  + "                  tblDctos.IDLOCAL         "
			  + "   AND ctrlUsuarios.idUsuario    =         "
			  + "               tblDctos.idVendedor         "
			  + "   INNER JOIN tblTercerosRuta              "
			  + "   ON tblTercerosRuta.idLocal    =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTercerosRuta.idRuta    =         "
			  + "                tblTerceros.idRuta         "
			  + "   INNER JOIN tblTerceroEstracto           "
			  + "   ON tblTerceroEstracto.idLocal =         "
			  + "               tblTerceros.IDLOCAL         "
			  + "   AND tblTerceroEstracto.idEstracto =     "
			  + "               tblTerceros.idEstracto      "
			  + "                  WHERE EXISTS             "                    
			  + "  ( SELECT *                               " 
			  + "    FROM   tblDctosOrdenes                 " 
			  + "    INNER JOIN tblDctosOrdenesDetalle      " 
			  + "    ON tblDctosOrdenes.IDLOCAL      =      " 
			  + "       tblDctosOrdenesDetalle.IDLOCAL      " 
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "   tblDctosOrdenesDetalle.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "       tblDctosOrdenesDetalle.IDORDEN      " 
			  + "    WHERE tblDctosOrdenes.IDLOCAL   =      " 
			  + "                     tblDctos.IDLOCAL      "
			  + "    AND tblDctosOrdenes.IDTIPOORDEN =      " 
			  + "                 tblDctos.IDTIPOORDEN      "
			  + "    AND tblDctosOrdenes.IDORDEN     =      " 
			  + "          tblDctos.IDORDEN)                "
			  + "    AND tblDctos.idLocal   =               " 
			  +" ?1                             "                
			  + "    AND tblDctos.idPeriodo =               "  
			  + "?2                           "                       
			  + " AND tblDctos.idTipoOrden  IN             ("
			  + "?3 ,                    "
			  + "?4 )                    "  
			  + " AND tblDctos.indicador BETWEEN            "
			  + "?5       AND          "
			  + "?6                     " 
			  + "    AND tblTerceros.IDTIPOTERCERO =1       "			 
			  + "    ORDER BY tblDctos.fechaDcto,           "      
			  + "             tblDctos.idTipoOrden,         "      
			  + "             tblDctos.idDcto",
              nativeQuery = true)
	  List<TblDctosDTO2> listaRepNotas(int idLocal, int idPeriodo, int IdTipoOrdenINI, int IdTipoOrdenFIN, int IndicadorINICIAL, int IndicadorFINNAL);
	  
	  
	  @Query(value = "SELECT tmpSaldo.idLocal,                "
              + "       tmpSaldo.IDTIPOORDEN,            "
              + "       tmpSaldo.idDcto,                 "
              + "       tmpSaldo.fechaDcto,              "
              + "       tmpSaldo.idCliente,              "
              + "       tblTerceros.idRuta,              "
              + "       tblTerceros.ordenRuta,           "
              + "      MAX(tmpSaldo.vrSaldo) AS vrSaldo, "
              + "       MAX(tmpSaldo.vrPago) AS vrPago,  "
              + "       MAX(tmpSaldo.idDctoNitCC)        "
              + "                        AS idDctoNitCC, "
              + "       MAX(tblTerceros.nombreTercero)   "
              + "                      AS nombreTercero, "
              + "      MAX(tblTerceros.direccionTercero) "
              + "                   AS direccionTercero, "
              + " MAX(tblTerceroEstracto.nombreEstracto) "
              + "                      AS nombreEstrato, "
              + "      MAX(tblTercerosRuta.nombreCiclo   "
              + "                            + '-' +     "
              + "      tblTercerosRuta.nombreRuta)       "
              + "                          AS nombreRuta,"
              + "       MAX(tblTerceros.CC_Nit)          "
              + "                        AS CC_Nit       "
              + " FROM                                   "
              + " (SELECT tmpCXC.IDLOCAL,                "
              + "         tmpCXC.IDTIPOORDEN,            "
              + "         tmpCXC.idDcto,                 "
              + "         tmpCXC.idOrden,                "
              + "         tmpCXC.indicador,              "
              + "         tmpCXC.idCliente,              "
              + "         MAX(tmpCXC.idDctoNitCC)        "
              + "                        AS idDctoNitCC, "
              + "         MAX(tmpCXC.diasPlazo)          "
              + "                          AS diasPlazo, "
              + "    MIN(tmpCXC.fechaDcto) AS fechaDcto, "
              + "    MIN(tmpCXC.fechaDcto) +             "
              + "    MAX(tmpCXC.diasPlazo) AS fechaVcto, "
              + "         SUM(tmpCXC.vrBase) AS vrBase,  "
              + "         SUM(tmpCXC.vrPago) AS vrPago,  "
              + "         SUM(tmpCXC.vrIva) AS vrIva,    "
              + "         SUM(tmpCXC.vrImpoconsumo)      "
              + "                      AS vrImpoconsumo, "
              + "         SUM(tmpCXC.vrRteFuente)        "
              + "                        AS vrRteFuente, "
              + "         SUM(tmpCXC.vrDsctoFcro)        "
              + "                        AS vrDsctoFcro, "
              + "      SUM(tmpCXC.vrRteIva) AS vrRteIva, "
              + "      SUM(tmpCXC.vrRteIca) AS vrRteIca, "
              + "     (SUM(tmpCXC.vrBase)      +         "
              + "      SUM(tmpCXC.vrIva)         +       "
              + "      SUM(tmpCXC.vrImpoconsumo) -       "
              + "      SUM(tmpCXC.vrPago)        -       "
              + "      SUM(tmpCXC.vrRteFuente)   -       "
              + "      SUM(tmpCXC.vrDsctoFcro)   -       "
              + "      SUM(tmpCXC.vrRteIva)      -       "
              + "      SUM(tmpCXC.vrRteIca)) AS vrSaldo  "
              + " FROM                                   "
              + " (SELECT tblDctos.idLocalCruce          "
              + "                            AS idLocal, "
              + "         tblDctos.idTipoOrdenCruce      "
              + "                        AS idTipoOrden, "
              + "        tblDctos.idDctoCruce AS idDcto, "
              + "      tblDctos.idOrdenCruce AS idOrden, "
              + "         tblDctos.indicador,            "
              + "         tblDctos.idCliente,            "
              + "         tblDctos.vrBase,               "
              + "         tblDctos.vrPago,               "
              + "         tblDctos.vrIva,                "
              + "         tblDctos.vrImpoconsumo,        "
              + "         tblDctos.vrRteFuente,          "
              + "         tblDctos.vrDsctoFcro,          "
              + "         tblDctos.vrRteIva,             "
              + "         tblDctos.vrRteIca,             "
              + "         tblDctos.fechaDcto,            "
              + "         tblDctos.diasPlazo,            "
              + "         tblDctos.idDctoNitCC           "
              + " FROM   tblDctos                        "
              + " WHERE  tblDctos.idLocal           =    "
              + "?1                          "
              + " AND    tblDctos.idTipoOrdenCruce  =    "
              + "?2                      "
              + " AND    tblDctos.idDctoCruce      != 0  "
              + " AND    tblDctos.idPeriodo         =    "
              + "?3                        "
              + " UNION                                  "
              + " SELECT tblDctos.idLocal,               "
              + "        tblDctos.idTipoOrden,           "
              + "        tblDctos.idDcto,                "
              + "        tblDctos.idOrden,               "
              + "        tblDctos.indicador,             "
              + "        tblDctos.idCliente,             "
              + "        tblDctos.vrBase,                "
              + "        tblDctos.vrPago,                "
              + "        tblDctos.vrIva,                 "
              + "        tblDctos.vrImpoconsumo,         "
              + "        tblDctos.vrRteFuente,           "
              + "        tblDctos.vrDsctoFcro,           "
              + "        tblDctos.vrRteIva,              "
              + "        tblDctos.vrRteIca,              "
              + "        tblDctos.fechaDcto,             "
              + "        tblDctos.diasPlazo,             "
              + "        tblDctos.idDctoNitCC            "
              + " FROM   tblDctos                        "
              + " WHERE  tblDctos.idLocal           =    "
              + "?1                          "
              + " AND    tblDctos.idTipoOrden       =    "
              + "?2                      "
              + " AND    tblDctos.idDctoCruce       = 0  "
              + " AND    tblDctos.idPeriodo         =    "
              + "?3                        "
              + " UNION                                  "
              + " SELECT tblDctos.idLocal,               "
              + "        tblDctos.idTipoOrden,           "
              + "        tblDctos.idDctoCruce AS idDcto, "
              + "      tblDctos.idOrdenCruce AS idOrden, "
              + "        tblDctos.indicador,             "
              + "        tblDctos.idCliente,             "
              + "        tblDctos.vrBase,                "
              + "        tblDctos.vrPago,                "
              + "        tblDctos.vrIva,                 "
              + "        tblDctos.vrImpoconsumo,         "
              + "        tblDctos.vrRteFuente,           "
              + "        tblDctos.vrDsctoFcro,           "
              + "        tblDctos.vrRteIva,              "
              + "        tblDctos.vrRteIca,              "
              + "        tblDctos.fechaDcto,             "
              + "        tblDctos.diasPlazo,             "
              + "        tblDctos.idDctoNitCC            "
              + " FROM   tblDctos                        "
              + " WHERE  tblDctos.idLocal           =    "
              + "?1                          "
              + " AND    tblDctos.idTipoOrden       =    "
              + "?2                      "
              + " AND    tblDctos.idTipoOrdenCruce  = 0  "
              + " AND    tblDctos.idDctoCruce      != 0  "
              + " AND    tblDctos.idPeriodo         =    "
              + "?3  )  AS tmpCXC          "
              + " GROUP BY tmpCXC.IDLOCAL,               "
              + "          tmpCXC.IDTIPOORDEN,           "
              + "          tmpCXC.idDcto,                "
              + "          tmpCXC.idOrden,               "
              + "          tmpCXC.indicador,             "
              + "          tmpCXC.idCliente              "
              + " HAVING (SUM(tmpCXC.vrBase) +           "
              + "  SUM(tmpCXC.vrIva)         +           "
              + "  SUM(tmpCXC.vrImpoconsumo) -           "
              + "  SUM(tmpCXC.vrPago)        -           "
              + "  SUM(tmpCXC.vrRteFuente)   -           "
              + "  SUM(tmpCXC.vrDsctoFcro)   -           "
              + "  SUM(tmpCXC.vrRteIva)      -           "
              + "  SUM(tmpCXC.vrRteIca) ) > 1 )          "
              + "               AS tmpSaldo              "
              + " INNER JOIN tblTerceros                 "
              + " ON  tmpSaldo.idLocal    =              "
              + "                    tblTerceros.idLocal "
              + " AND tmpSaldo.idCliente  =              "
              + "                  tblTerceros.idCliente "
              + " INNER JOIN tblTerceroEstracto          "
              + " ON tblTerceros.idLocal =               "
              + "             tblTerceroEstracto.idLocal "
              + " AND tblTerceros.idEstracto =           "
              + "          tblTerceroEstracto.idEstracto "
              + " INNER JOIN tblTercerosRuta             "
              + " ON tblTerceros.idLocal =               "
              + "                tblTercerosRuta.idLocal "
              + " AND tblTerceros.idRuta =               "
              + "                tblTercerosRuta.idRuta  "
              + " AND EXISTS                             "
              + "  (SELECT *                             "
              + "   FROM   tblDctosOrdenes               "
              + "   INNER JOIN tblDctosOrdenesDetalle    "
              + "   ON tblDctosOrdenes.IDLOCAL      =    "
              + "         tblDctosOrdenesDetalle.IDLOCAL "
              + "   AND tblDctosOrdenes.IDTIPOORDEN =    "
              + "     tblDctosOrdenesDetalle.IDTIPOORDEN "
              + "   AND tblDctosOrdenes.IDORDEN     =    "
              + "         tblDctosOrdenesDetalle.IDORDEN "
              + "   WHERE tblDctosOrdenes.IDLOCAL   =    "
              + "         tblDctosOrdenesDetalle.IDLOCAL "
              + "   AND tblDctosOrdenes.IDTIPOORDEN =    "
              + "     tblDctosOrdenesDetalle.IDTIPOORDEN "
              + "   AND tblDctosOrdenes.IDORDEN =        "
              + "         tblDctosOrdenesDetalle.IDORDEN "
              + "   AND tblDctosOrdenes.idLocal  =       "
              + "                       tmpSaldo.idLocal "
              + "   AND tblDctosOrdenes.IDTIPOORDEN    = "
              + "                   tmpSaldo.IDTIPOORDEN "
              + "   AND tblDctosOrdenes.IDORDEN  =       "
              + "                      tmpSaldo.IDORDEN) "
              + " WHERE tblTerceros.idTipoTercero = 1	   "
              + " AND tblTerceros.idLocal =              "
              + "?1                            "
              + " GROUP BY tmpSaldo.idLocal,             "
              + "          tmpSaldo.IDTIPOORDEN,         "
              + "          tmpSaldo.idDcto,              "
              + "          tmpSaldo.fechaDcto,           "
              + "          tmpSaldo.fechaVcto,           "
              + "          tmpSaldo.idCliente,           "
              + "          tblTerceros.idRuta ,          "
              + "          tblTerceros.ordenRuta         "
              + " ORDER BY tblTerceros.idRuta,           "
              + " 	     tblTerceros.ordenRuta",
              nativeQuery = true)
	  List<TblDctosDTO> listaCxCPeriodoAll(int idLocal, int xIdTipoOrden, int idPeriodo);
	  
	  
	  
	  
	  @Query(value = " SELECT tmpSaldo.idLocal,                     "
              + "  tmpSaldo.IDTIPOORDEN,                       "
              + "  tmpSaldo.idDcto,                            "
              + "  tmpSaldo.fechaDcto,                         "
              + "  tmpSaldo.idCliente,                         "
              + "  tblTerceros.idRuta,                         "
              + "  tblTerceros.ordenRuta,                      "
              + "  MAX(tmpSaldo.vrSaldo) AS vrSaldo,           "
              + "  MAX(tmpSaldo.vrPago) AS vrPago,      	 "
              + "  MAX(tmpSaldo.idDctoNitCC) AS idDctoNitCC,   "
              + "  MAX(tblTerceros.nombreTercero)              "
              + "                            AS nombreTercero, "
              + "  MAX(tblTerceros.direccionTercero)           "
              + "                         AS direccionTercero, "
              + "  MAX(tblTerceroEstracto.nombreEstracto)      "
              + "                            AS nombreEstrato, "
              + "  MAX(tblTercerosRuta.nombreCiclo             "
              + "                          + '-' +             "
              + "   tblTercerosRuta.nombreRuta) AS nombreRuta  "
              + " FROM                                         "
              + " (SELECT tmpCXC.IDLOCAL,                      "
              + "         tmpCXC.IDTIPOORDEN,                  "
              + "         tmpCXC.idDcto,                       "
              + "         tmpCXC.idOrden,                      "
              + "         tmpCXC.indicador,                    "
              + "         tmpCXC.idCliente,                    "
              + "         MAX(tmpCXC.idDctoNitCC)              "
              + "                              AS idDctoNitCC, "
              + "         MAX(tmpCXC.diasPlazo) AS diasPlazo,  "
              + "         MIN(tmpCXC.fechaDcto) AS fechaDcto,  "
              + "         MIN(tmpCXC.fechaDcto) +              "
              + "          MAX(tmpCXC.diasPlazo) AS fechaVcto, "
              + "         SUM(tmpCXC.vrBase) AS vrBase,        "
              + "         SUM(tmpCXC.vrPago) AS vrPago,        "
              + "         SUM(tmpCXC.vrIva) AS vrIva,          "
              + "         SUM(tmpCXC.vrImpoconsumo)            "
              + "                            AS vrImpoconsumo, "
              + "         SUM(tmpCXC.vrRteFuente)              "
              + "                              AS vrRteFuente, "
              + "         SUM(tmpCXC.vrDsctoFcro)              "
              + "                              AS vrDsctoFcro, "
              + "         SUM(tmpCXC.vrRteIva) AS vrRteIva,    "
              + "         SUM(tmpCXC.vrRteIca) AS vrRteIca,    "
              + "        ( SUM(tmpCXC.vrBase)      +           "
              + "          SUM(tmpCXC.vrIva)         +         "
              + "          SUM(tmpCXC.vrImpoconsumo) -         "
              + "          SUM(tmpCXC.vrPago)        -         "
              + "          SUM(tmpCXC.vrRteFuente)   -         "
              + "          SUM(tmpCXC.vrDsctoFcro)   -         "
              + "          SUM(tmpCXC.vrRteIva)      -         "
              + "          SUM(tmpCXC.vrRteIca) ) AS vrSaldo   "
              + " FROM                                         "
              + " (SELECT tblDctos.idLocalCruce AS idLocal,    "
              + "         tblDctos.idTipoOrdenCruce            "
              + "                              AS idTipoOrden, "
              + "         tblDctos.idDctoCruce AS idDcto,      "
              + "         tblDctos.idOrdenCruce AS idOrden,    "
              + "         tblDctos.indicador,                  "
              + "         tblDctos.idCliente,                  "
              + "         tblDctos.vrBase,                     "
              + "         tblDctos.vrPago,                     "
              + "         tblDctos.vrIva,                      "
              + "         tblDctos.vrImpoconsumo,              "
              + "         tblDctos.vrRteFuente,                "
              + "         tblDctos.vrDsctoFcro,                "
              + "         tblDctos.vrRteIva,                   "
              + "         tblDctos.vrRteIca,                   "
              + "         tblDctos.fechaDcto,                  "
              + "         tblDctos.diasPlazo,                  "
              + "         tblDctos.idDctoNitCC                 "
              + " FROM   tblDctos                              "
              + " INNER JOIN                                   "
              + " ( SELECT tblTerceros.idLocal,                "
              + "        tblTerceros.idCliente,                "
              + "        MAX(tblDctos.idPeriodo) AS idPeriodo  "
              + "   FROM tblTerceros                           "
              + "   INNER JOIN tblDctos                        "
              + "   ON tblDctos.idLocal  = tblTerceros.idLocal "
              + "   AND tblDctos.idCliente =                   "
              + "                       tblTerceros.idCliente  "
              + "   WHERE tblTerceros.idLocal =                "
              + "?1                                "
              + "   AND tblDctos.idTipoOrden  =                "
              + "?2                            "
              + "   AND tblTerceros.estado    = 2              "
              + "   GROUP BY tblTerceros.idLocal,              "
              + "        tblTerceros.idCliente ) AS tmpTER     "
              + " ON tmpTER.idLocal = tblDctos.idLocal         "
              + " AND tmpTER.idPeriodo =  tblDctos.idPeriodo 	 "
              + " AND tmpTER.idCliente = tblDctos.idCliente 	 "
              + " WHERE  tblDctos.idLocal           =          "
              + "?1                               "
              + " AND    tblDctos.idTipoOrdenCruce  =          "
              + "?2                            "
              + " AND    tblDctos.idDctoCruce      != 0        "
              + " UNION                                        "
              + " SELECT tblDctos.idLocal,                     "
              + "    tblDctos.idTipoOrden,                     "
              + "    tblDctos.idDcto,                          "
              + "    tblDctos.idOrden,                         "
              + "    tblDctos.indicador,                       "
              + "    tblDctos.idCliente,                       "
              + "    tblDctos.vrBase,                          "
              + "    tblDctos.vrPago,                          "
              + "    tblDctos.vrIva,                           "
              + "    tblDctos.vrImpoconsumo,                   "
              + "    tblDctos.vrRteFuente,                     "
              + "    tblDctos.vrDsctoFcro,                     "
              + "    tblDctos.vrRteIva,                        "
              + "    tblDctos.vrRteIca,                        "
              + "    tblDctos.fechaDcto,                       "
              + "    tblDctos.diasPlazo,                       "
              + "    tblDctos.idDctoNitCC                      "
              + " FROM   tblDctos                              "
              + " INNER JOIN                                   "
              + " ( SELECT tblTerceros.idLocal,                "
              + "        tblTerceros.idCliente,                "
              + "        MAX(tblDctos.idPeriodo) AS idPeriodo  "
              + "   FROM tblTerceros                           "
              + "   INNER JOIN tblDctos                        "
              + "   ON tblDctos.idLocal = tblTerceros.idLocal  "
              + "   AND tblDctos.idCliente =                   "
              + "                        tblTerceros.idCliente "
              + "   WHERE tblTerceros.idLocal =                "
              + "?1                               "
              + "   AND tblDctos.idTipoOrden  =                "
              + "?2                             "
              + "   AND tblTerceros.estado    = 2              "
              + "   GROUP BY tblTerceros.idLocal,              "
              + "        tblTerceros.idCliente) AS tmpTER      "
              + " ON tmpTER.idLocal = tblDctos.idLocal         "
              + " AND tmpTER.idPeriodo = tblDctos.idPeriodo 	 "
              + " AND tmpTER.idCliente = tblDctos.idCliente 	 "
              + " WHERE  tblDctos.idLocal           =          "
              + "?1                              "
              + "  AND    tblDctos.idTipoOrden       =         "
              + "?2                            "
              + "  AND    tblDctos.idDctoCruce       = 0       "
              + "  UNION                                       "
              + "  SELECT tblDctos.idLocal,                    "
              + "   tblDctos.idTipoOrden,                      "
              + "   tblDctos.idDctoCruce AS idDcto,            "
              + "   tblDctos.idOrdenCruce AS idOrden,          "
              + "   tblDctos.indicador,                        "
              + "   tblDctos.idCliente,                        "
              + "   tblDctos.vrBase,                           "
              + "   tblDctos.vrPago,                           "
              + "   tblDctos.vrIva,                            "
              + "   tblDctos.vrImpoconsumo,                    "
              + "   tblDctos.vrRteFuente,                      "
              + "   tblDctos.vrDsctoFcro,                      "
              + "   tblDctos.vrRteIva,                         "
              + "   tblDctos.vrRteIca,                         "
              + "   tblDctos.fechaDcto,                        "
              + "   tblDctos.diasPlazo,                        "
              + "   tblDctos.idDctoNitCC                       "
              + "  FROM   tblDctos                             "
              + " INNER JOIN                                   "
              + " ( SELECT tblTerceros.idLocal,                "
              + "        tblTerceros.idCliente,                "
              + "        MAX(tblDctos.idPeriodo) AS idPeriodo  "
              + "   FROM tblTerceros                           "
              + "   INNER JOIN tblDctos                        "
              + "   ON tblDctos.idLocal  = tblTerceros.idLocal "
              + "   AND tblDctos.idCliente    =                "
              + "                        tblTerceros.idCliente "
              + "   WHERE tblTerceros.idLocal =                "
              + "?1                                "
              + "   AND tblDctos.idTipoOrden  =                "
              + "?2                           "
              + "   AND tblTerceros.estado    = 2              "
              + "   GROUP BY tblTerceros.idLocal,              "
              + "        tblTerceros.idCliente ) AS tmpTER     "
              + " ON tmpTER.idLocal = tblDctos.idLocal         "
              + " AND tmpTER.idPeriodo = tblDctos.idPeriodo 	 "
              + " AND tmpTER.idCliente =  tblDctos.idCliente 	 "
              + "  WHERE  tblDctos.idLocal           =         "
              + "?1                               "
              + "   AND    tblDctos.idTipoOrden       =        "
              + "?2                            "
              + "   AND tblDctos.idTipoOrdenCruce  = 0         "
              + "   AND tblDctos.idDctoCruce != 0 ) AS tmpCXC  "
              + "   GROUP BY tmpCXC.IDLOCAL,                   "
              + "    tmpCXC.IDTIPOORDEN,                       "
              + "    tmpCXC.idDcto,                            "
              + "    tmpCXC.idOrden,                           "
              + "    tmpCXC.indicador,                         "
              + "    tmpCXC.idCliente                          "
              + "   HAVING ( SUM(tmpCXC.vrBase) +              "
              + "    SUM(tmpCXC.vrIva)         +               "
              + "    SUM(tmpCXC.vrImpoconsumo) -               "
              + "    SUM(tmpCXC.vrPago)        -               "
              + "    SUM(tmpCXC.vrRteFuente)   -               "
              + "    SUM(tmpCXC.vrDsctoFcro)   -               "
              + "    SUM(tmpCXC.vrRteIva)      -               "
              + "    SUM(tmpCXC.vrRteIca) ) > 1 ) AS tmpSaldo  "
              + "   INNER JOIN tblTerceros                     "
              + "   ON tmpSaldo.idLocal = tblTerceros.idLocal  "
              + "   AND tmpSaldo.idCliente  =                  "
              + "                       tblTerceros.idCliente  "
              + "   INNER JOIN tblTerceroEstracto              "
              + "   ON  tblTerceros.idLocal =                  "
              + "                  tblTerceroEstracto.idLocal  "
              + "   AND  tblTerceros.idEstracto =              "
              + "               tblTerceroEstracto.idEstracto  "
              + "   INNER JOIN tblTercerosRuta                 "
              + "   ON  tblTerceros.idLocal =                  "
              + "                      tblTercerosRuta.idLocal "
              + "   AND  tblTerceros.idRuta =                  "
              + "                      tblTercerosRuta.idRuta  "
              + "   WHERE tblTerceros.idTipoTercero = 1	 "
              + "   AND tblTerceros.idLocal         =          "
              + "?1                               "
              + "   AND tblTerceros.estado          = 2        "
              + "   GROUP BY tmpSaldo.idLocal,                 "
              + "   tmpSaldo.IDTIPOORDEN,                      "
              + "   tmpSaldo.idDcto,                           "
              + "   tmpSaldo.fechaDcto,                        "
              + "   tmpSaldo.fechaVcto,                        "
              + "   tmpSaldo.idCliente,                        "
              + "   tblTerceros.idRuta ,                       "
              + "   tblTerceros.ordenRuta                      "
              + "   ORDER BY tblTerceros.idRuta,               "
              + "   	       tblTerceros.ordenRuta ",
              nativeQuery = true)
	  List<TblDctosDTO> listaCxCSuspendidoAll(int idLocal, int xIdTipoOrden);
	  
	  
	  
	  @Query(value = "SELECT tblDctos.idCliente AS idCliente,            "
              + "       MAX(tblTerceros.CC_Nit) AS ccNit,      "
              + "       MAX(tblTerceros.nombreTercero)         "
              + "	                 AS nombreTercero,       "
              + "	  MAX(tblTerceros.direccionTercero)      "
              + "                     AS direccionTercero,     "
              + "  CAST(SUM(tblDctosOrdenesDetalle.cantidad *  "
              + "      tblDctosOrdenesDetalle.vrVentaUnitario) "
              + "		    AS DECIMAL(16,2)) AS vrBase "
              + "FROM  tblTerceros                             "
              + "INNER JOIN tblDctos                           "
              + "ON tblTerceros.idLocal = tblDctos.IDLOCAL     "
              + "AND tblTerceros.idCliente =                   "
              + "                           tblDctos.idCliente "
              + "INNER JOIN tblDctosOrdenesDetalle             "
              + "ON tblDctosOrdenesDetalle.idLocal  =          "
              + "                             tblDctos.IDLOCAL "
              + "AND tblDctosOrdenesDetalle.idTipoOrden        "
              + "                       = tblDctos.idTipoOrden "
              + "AND tblDctosOrdenesDetalle.idOrden =          "
              + "                             tblDctos.idOrden "
              + "WHERE tblTerceros.idLocal          =          "
              + "?1                                "
              + "AND   tblDctos.IDTIPOORDEN         IN ("
              + "?2 , ?3 )             "
              + "AND   tblDctos.idPeriodo      BETWEEN "
              + "?4  AND           "
              + "?5                 "
              + "AND   tblDctos.indicador =                    "
              + "?6                       "
              + "AND tblDctosOrdenesDetalle.idTipo < 100       "
              + "GROUP BY tblDctos.idCliente                   "
              + "HAVING SUM(tblDctos.vrBase)!=0                "
              + "ORDER BY 3 ",
              nativeQuery = true)
	  List<TblDctosDTO> listaRepMediosMagneticosDian(int idLocal, int IdTipoOrdenINI, int IdTipoOrdenFIN, int IdPeriodoInicial, int IdPeriodoFinal, int Indicador);
	  
	  
	  
	  
	  @Query(value = "SELECT tmpSaldo.idLocal,                      "
              + "       tmpSaldo.IDTIPOORDEN,                  "
              + "       tmpSaldo.idDcto,                       "
              + "       tmpSaldo.fechaDcto,                    "
              + "       tmpSaldo.fechaVcto,                    "
              + "       tmpSaldo.idCliente,                    "
              + "       tmpSaldo.diasVcto AS diasMora,         "
              + "       tmpSaldo.vrSaldo,                      "
              + "       tmpSaldo.indicador,                    "
              + "       MAX(tmpSaldo.idDctoNitCC)              "
              + "                             AS idDctoNitCC,  "
              + "       MAX(tmpSaldo.nombreTercero)            "
              + "                            AS nombreTercero, "
              + "       DATEDIFF(DAY,tmpSaldo.fechaDcto,      "
              + "?1 ) AS edadFra,                  "
              + "       MAX(tmpSaldo.nombreVendedor)           "
              + "                            AS nombreVendedor, "
              + "       tmpSaldo.nombreRuta,                   "
              + "       tmpSaldo.nombreEstrato                 "
              + "FROM                                          "
              + "(SELECT tmpCXC.IDLOCAL,                       "
              + "        tmpCXC.IDTIPOORDEN,                   "
              + "        tmpCXC.idDcto,                        "
              + "        tmpCXC.idOrden,                       "
              + "       tmpCXC.indicador,                      "
              + "       tmpCXC.idCliente,                      "
              + "       MAX(tmpCXC.idDctoNitCC)                "
              + "                             AS idDctoNitCC,  "
              + "       MAX(tmpCXC.diasPlazo) AS diasPlazo,    "
              + "       MIN(tmpCXC.fechaDcto) AS fechaDcto,    "
              + "       MIN(tmpCXC.fechaDcto) +                "
              + "       MAX(tmpCXC.diasPlazo) AS fechaVcto,    "
              + "       DATEDIFF(DAY,  MIN(tmpCXC.fechaDcto) + "
              + "             MAX(tmpCXC.diasPlazo),          "
              + "?1 ) AS diasVcto,                 "
              + "       SUM(tmpCXC.vrBase) AS vrBase,          "
              + "       SUM(tmpCXC.vrPago) AS vrPago,          "
              + "       SUM(tmpCXC.vrIva) AS vrIva,            "
              + "       SUM(tmpCXC.vrImpoconsumo)              "
              + "                          AS vrImpoconsumo,   "
              + "       SUM(tmpCXC.vrRteFuente) AS vrRteFuente,"
              + "       SUM(tmpCXC.vrDsctoFcro) AS vrDsctoFcro,"
              + "       SUM(tmpCXC.vrRteIva) AS vrRteIva,      "
              + "       SUM(tmpCXC.vrRteIca) AS vrRteIca,      "
              + "       ( SUM(tmpCXC.vrBase)               +   "
              + "                SUM(tmpCXC.vrIva)         +   "
              + "                SUM(tmpCXC.vrImpoconsumo) -   "
              + "                SUM(tmpCXC.vrPago)        -   "
              + "                SUM(tmpCXC.vrRteFuente)   -   "
              + "                SUM(tmpCXC.vrDsctoFcro)   -   "
              + "                SUM(tmpCXC.vrRteIva)      -   "
              + "         SUM(tmpCXC.vrRteIca) ) AS vrSaldo,   "
              + "         MAX(tmpCXC.nombreTercero)            "
              + "                             AS nombreTercero,"
              + "         MAX(tmpCXC.idVendedor) AS idVendedor,"
              + "         MAX(tmpCXC.nombreVendedor)           "
              + "                            AS nombreVendedor, "
              + "         tmpCXC.nombreRuta,	                 "
              + "	   tmpCXC.nombreEstrato          	 "
              + "FROM                                          "
              + "(SELECT tblDctos.idLocalCruce                 "
              + "                      AS idLocal,             "
              + "       tblDctos.idTipoOrdenCruce              "
              + "                  AS idTipoOrden,             "
              + "       tblDctos.idDctoCruce                   "
              + "                      AS idDcto,              "
              + "       tblDctos.idOrdenCruce AS idOrden,      "
              + "       tblDctos.indicador,                    "
              + "       tblDctos.idCliente,                    "
              + "       tblDctos.vrBase,                       "
              + "       tblDctos.vrPago,                       "
              + "       tblDctos.vrIva,                        "
              + "       tblDctos.vrImpoconsumo,                "
              + "       tblDctos.vrRteFuente,                  "
              + "       tblDctos.vrDsctoFcro,                  "
              + "       tblDctos.vrRteIva,                     "
              + "       tblDctos.vrRteIca,                     "
              + "       tblDctos.fechaDcto,                    "
              + "       tblDctos.diasPlazo,                    "
              + "       tblDctos.idDctoNitCC,                  "
              + "       tblDctos.nombreTercero,                "
              + "       tblDctos.idVendedor,                   "
              + "       (SELECT ctrlUsuarios.aliasUsuario      "
              + "        FROM ctrlUsuarios                     "
              + "        WHERE ctrlUsuarios.idUsuario  =       "
              + "                        tblDctos.idVendedor   "
              + "        AND ctrlUsuarios.idLocal      =       "
              + "                           tblDctos.idLocal)  "
              + "                            AS nombreVendedor, "
              + "       (SELECT tblTercerosRuta.nombreRuta     "
              + "	   FROM tblTercerosRuta                  "
              + "	   INNER JOIN tblTerceros                "
              + "        ON tblTercerosRuta.idLocal            "
              + "			 = tblTerceros.idLocal   "
              + "	   AND tblTercerosRuta.idRuta            "
              + "	                  =tblTerceros.idRuta    "
              + "	   WHERE tblTerceros.idLocal             "
              + "			  = tblDctos.IDLOCAL     "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "				AS nombreRuta,   "
              + "    (SELECT tblTerceroEstracto.nombreEstracto "
              + "	   FROM tblTerceroEstracto               "
              + "        INNER JOIN tblTerceros                "
              + "	   ON tblTerceroEstracto.idLocal         "
              + "		          =tblTerceros.idLocal   "
              + "	   AND tblTerceroEstracto.idEstracto     "
              + "			=tblTerceros.idEstracto  "
              + "	   WHERE tblTerceros.idLocal             "
              + "		         = tblDctos.IDLOCAL      "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "			       AS nombreEstrato  "
              + "FROM   tblDctos                               "
              + "WHERE  tblDctos.idLocal           =           "
              + "?2                           "
              + "AND    tblDctos.idTipoOrdenCruce  =           "
              + "?3                       "
              + "AND    tblDctos.idDctoCruce      != 0         "
              + "AND    tblDctos.idPeriodo         =           "
              + "?4                         "
              + "AND    EXISTS (                               "
              + "       SELECT *                               "
              + "       FROM tblDctosOrdenesDetalle            "
              + "       WHERE tblDctosOrdenesDetalle.idLocal = "
              + "                            tblDctos.idLocal  "
              + "       AND tblDctosOrdenesDetalle.idTipoOrden "
              + "                                            = "
              + "                       tblDctos.idTipoOrden   "
              + "      AND  tblDctosOrdenesDetalle.idOrden   = "
              + "                           tblDctos.idOrden ) "
              + "UNION                                         "
              + "SELECT tblDctos.idLocal,                      "
              + "       tblDctos.idTipoOrden,                  "
              + "       tblDctos.idDcto,                       "
              + "       tblDctos.idOrden,                      "
              + "       tblDctos.indicador,                    "
              + "       tblDctos.idCliente,                    "
              + "       tblDctos.vrBase,                       "
              + "       tblDctos.vrPago,                       "
              + "       tblDctos.vrIva,                        "
              + "       tblDctos.vrImpoconsumo,                "
              + "       tblDctos.vrRteFuente,                  "
              + "       tblDctos.vrDsctoFcro,                  "
              + "       tblDctos.vrRteIva,                     "
              + "       tblDctos.vrRteIca,                     "
              + "       tblDctos.fechaDcto,                    "
              + "       tblDctos.diasPlazo,                    "
              + "       tblDctos.idDctoNitCC,                  "
              + "       tblDctos.nombreTercero,                "
              + "       tblDctos.idVendedor,                   "
              + "       (SELECT ctrlUsuarios.aliasUsuario      "
              + "        FROM ctrlUsuarios                     "
              + "        WHERE ctrlUsuarios.idUsuario  =       "
              + "                        tblDctos.idVendedor   "
              + "        AND ctrlUsuarios.idLocal      =       "
              + "                           tblDctos.idLocal)  "
              + "                            AS nombreVendedor, "
              + "       (SELECT tblTercerosRuta.nombreRuta     "
              + "	   FROM tblTercerosRuta                  "
              + "	   INNER JOIN tblTerceros                "
              + "        ON tblTercerosRuta.idLocal            "
              + "			 = tblTerceros.idLocal   "
              + "	   AND tblTercerosRuta.idRuta            "
              + "	                  =tblTerceros.idRuta    "
              + "	   WHERE tblTerceros.idLocal             "
              + "			  = tblDctos.IDLOCAL     "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "				AS nombreRuta,   "
              + "    (SELECT tblTerceroEstracto.nombreEstracto "
              + "	   FROM tblTerceroEstracto               "
              + "        INNER JOIN tblTerceros                "
              + "	   ON tblTerceroEstracto.idLocal         "
              + "		          =tblTerceros.idLocal   "
              + "	   AND tblTerceroEstracto.idEstracto     "
              + "			=tblTerceros.idEstracto  "
              + "	   WHERE tblTerceros.idLocal             "
              + "		         = tblDctos.IDLOCAL      "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "			       AS nombreEstrato  "
              + "FROM   tblDctos                               "
              + "WHERE  tblDctos.idLocal           =           "
              + "?2                          "
              + "AND    tblDctos.idTipoOrden       =           "
              + "?3                       "
              + "AND    tblDctos.idDctoCruce       = 0         "
              + "AND    tblDctos.idPeriodo         =           "
              + "?4                         "
              + "AND    EXISTS (                               "
              + "       SELECT *                               "
              + "       FROM tblDctosOrdenesDetalle            "
              + "       WHERE tblDctosOrdenesDetalle.idLocal = "
              + "                            tblDctos.idLocal  "
              + "       AND tblDctosOrdenesDetalle.idTipoOrden "
              + "                                            = "
              + "                       tblDctos.idTipoOrden   "
              + "      AND  tblDctosOrdenesDetalle.idOrden   = "
              + "                           tblDctos.idOrden ) "
              + "UNION                                         "
              + "SELECT tblDctos.idLocal,                      "
              + "       tblDctos.idTipoOrden,                  "
              + "       tblDctos.idDctoCruce                   "
              + "                      AS idDcto,              "
              + "       tblDctos.idOrdenCruce AS idOrden,      "
              + "       tblDctos.indicador,                    "
              + "       tblDctos.idCliente,                    "
              + "       tblDctos.vrBase,                       "
              + "       tblDctos.vrPago,                       "
              + "       tblDctos.vrIva,                        "
              + "       tblDctos.vrImpoconsumo,                "
              + "       tblDctos.vrRteFuente,                  "
              + "       tblDctos.vrDsctoFcro,                  "
              + "       tblDctos.vrRteIva,                     "
              + "       tblDctos.vrRteIca,                     "
              + "       tblDctos.fechaDcto,                    "
              + "       tblDctos.diasPlazo,                    "
              + "       tblDctos.idDctoNitCC,                  "
              + "       tblDctos.nombreTercero,                "
              + "       tblDctos.idVendedor,                   "
              + "       (SELECT ctrlUsuarios.aliasUsuario      "
              + "        FROM ctrlUsuarios                     "
              + "        WHERE ctrlUsuarios.idUsuario  =       "
              + "                        tblDctos.idVendedor   "
              + "        AND ctrlUsuarios.idLocal      =       "
              + "                           tblDctos.idLocal)  "
              + "                            AS nombreVendedor, "
              + "       (SELECT tblTercerosRuta.nombreRuta     "
              + "	   FROM tblTercerosRuta                  "
              + "	   INNER JOIN tblTerceros                "
              + "        ON tblTercerosRuta.idLocal            "
              + "			 = tblTerceros.idLocal   "
              + "	   AND tblTercerosRuta.idRuta            "
              + "	                  =tblTerceros.idRuta    "
              + "	   WHERE tblTerceros.idLocal             "
              + "			  = tblDctos.IDLOCAL     "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "				AS nombreRuta,   "
              + "    (SELECT tblTerceroEstracto.nombreEstracto "
              + "	   FROM tblTerceroEstracto               "
              + "        INNER JOIN tblTerceros                "
              + "	   ON tblTerceroEstracto.idLocal         "
              + "		          =tblTerceros.idLocal   "
              + "	   AND tblTerceroEstracto.idEstracto     "
              + "			=tblTerceros.idEstracto  "
              + "	   WHERE tblTerceros.idLocal             "
              + "		         = tblDctos.IDLOCAL      "
              + "        AND tblTerceros.idCliente             "
              + "			= tblDctos.idCliente)    "
              + "			       AS nombreEstrato  "
              + "FROM   tblDctos                               "
              + "WHERE  tblDctos.idLocal           =           "
              + "?2                          "
              + "AND    tblDctos.idTipoOrden       =           "
              + "?3                     "
              + "AND    tblDctos.idTipoOrdenCruce  = 0         "
              + "AND    tblDctos.idDctoCruce      != 0         "
              + "AND    tblDctos.idPeriodo         =           "
              + "?4                        "
              + "AND    EXISTS (                               "
              + "       SELECT *                               "
              + "       FROM tblDctosOrdenesDetalle            "
              + "       WHERE tblDctosOrdenesDetalle.idLocal = "
              + "                            tblDctos.idLocal  "
              + "       AND tblDctosOrdenesDetalle.idTipoOrden "
              + "                                            = "
              + "                       tblDctos.idTipoOrden   "
              + "      AND  tblDctosOrdenesDetalle.idOrden   = "
              + "                           tblDctos.idOrden ) "
              + "                          )  AS tmpCXC        "
              + "GROUP BY tmpCXC.IDLOCAL,                      "
              + "         tmpCXC.IDTIPOORDEN,                  "
              + "         tmpCXC.idDcto,                       "
              + "         tmpCXC.idOrden,                      "
              + "         tmpCXC.indicador,                    "
              + "         tmpCXC.idCliente,                     "
              + "	    tmpCXC.nombreRuta,                   "
              + "    	    tmpCXC.nombreEstrato                 "
              + "HAVING ( SUM(tmpCXC.vrBase)        +          "
              + "         SUM(tmpCXC.vrIva)         +          "
              + "         SUM(tmpCXC.vrImpoconsumo) -          "
              + "         SUM(tmpCXC.vrPago)        -          "
              + "         SUM(tmpCXC.vrRteFuente)   -          "
              + "         SUM(tmpCXC.vrDsctoFcro)   -          "
              + "         SUM(tmpCXC.vrRteIva)      -          "
              + "         SUM(tmpCXC.vrRteIca) ) < 0 )         "
              + "                              AS tmpSaldo     "
              + "WHERE    tmpSaldo.indicador BETWEEN           "
              + "?5 AND             "
              + "?6                   "
              + "GROUP BY tmpSaldo.idLocal,                    "
              + "         tmpSaldo.IDTIPOORDEN,                "
              + "         tmpSaldo.idDcto,                     "
              + "         tmpSaldo.fechaDcto,                  "
              + "         tmpSaldo.fechaVcto,                  "
              + "         tmpSaldo.idCliente,                  "
              + "         tmpSaldo.diasVcto,                   "
              + "         tmpSaldo.vrSaldo,                    "
              + "         tmpSaldo.indicador,                   "
              + "       tmpSaldo.nombreRuta,                   "
              + "	tmpSaldo.nombreEstrato                   "
              + "ORDER BY tmpSaldo.fechaDcto                   ",
              nativeQuery = true)
	  List<TblDctosDTO> listaSaldoFavor(String fecha, int idLocal, int IdTipoOrden, int IdPeriodo, int IndicadorInicial, int IndicadorFinal );
	  
	  
	  
	  
	  @Query(value = "SELECT idCliente " +
              "FROM bdaquamovil.dbo.tblDctos " +
              "WHERE tblDctos.IDLOCAL = ?1 " +
              "AND tblDctos.idDcto = ?2 " +
              "AND tblDctos.IDTIPOORDEN = 9 " +
              "AND tblDctos.indicador = 1 ",
              nativeQuery = true)
	  String ObtenerIdCliente(int idLocal, int idDcto);
	  
}
