package com.marketing.Repository.dbaquamovil;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.marketing.Model.dbaquamovil.TblPagos;
import com.marketing.Projection.TblPagosDTO;

@Repository
public interface TblPagosRepo extends JpaRepository<TblPagos, Integer> {

	
	  @Modifying
	  @Transactional
	  @Query(value = "DELETE FROM tblpagos " +
	                 "WHERE tblpagos.idLocal  =  ?1 " +
	                 "AND  tblpagos.idTipoOrden IN (7,9,29, 59) " +
	                 "AND  tblpagos.idPeriodo  = ?2 ", nativeQuery = true)
	  public void retiraPago(int idLocal, int idPeriodo);
	  
	  
	  
	  @Query(value = " SELECT tblpagos.nitCC AS idCliente,       "
              + "        tblterceros.nombreTercero,         "
              + "        tblpagos.idLocal,                  "
              + "        tblpagos.idTipoOrden,              "
              + "        tblpagos.idRecibo,                 "
              + "        tblpagos.indicador,                "
              + "        tblpagos.fechaPago,                "
              + "        tmpMED.vrMedio AS vrPago,          "
              + "        tblpagos.vrRteFuente,              "
              + "        tblpagos.vrDescuento,              "
              + "        tblpagos.vrRteIva,                 "
              + "        tblpagos.idDcto,                   "
              + "        tblpagos.idDctoNitCC,              "
              + "        tblpagos.idPlanilla,               "
              + "        tblpagos.vrRteIca,                 "
              + "        tbltercerosruta.nombreCiclo        "
              + "                            + ' / ' +      "
              + "        tbltercerosruta.nombreRuta         "
              + "                           AS nombreRuta,  "
              + "        tblterceroestracto.nombreEstracto, "
              + "        tblpagos.idPeriodo,                "
              + "        ctrlusuarios.nombreUsuario         "
              + "                        AS aliasUsuario,   "
              + "        tmpMED.idMedio,                    "
              + "        tblmediospago.nombreMedio,         "
              + "        tblTerceros.CC_Nit                 "
              + " FROM tblpagos                             "
              + " INNER JOIN tblterceros                    "
              + " ON tblpagos.idLocal = tblterceros.idLocal "
              + " AND tblpagos.nitCC =                      "
              + "                     tblterceros.idCliente "
              + " INNER JOIN tblterceroestracto             "
              + " ON tblterceros.idLocal     =              "
              + "               tblterceroestracto.idLocal  "
              + " AND tblterceros.idEstracto =              "
              + "            tblterceroestracto.idEstracto  "
              + " INNER JOIN tbltercerosruta                "
              + " ON tblterceros.idLocal  =                 "
              + "                   tbltercerosruta.idLocal "
              + " AND tblterceros.idRuta     =              "
              + "                    tbltercerosruta.idRuta "
              + " INNER JOIN ctrlusuarios                   "
              + " ON tblpagos.idLocal =                     "
              + "                      ctrlusuarios.idLocal "
              + " AND tblpagos.idUsuario =                  "
              + "                  ctrlusuarios.idUsuario   "
              + " INNER JOIN			              "
              + " ( SELECT  idLocal                         "
              + "       ,idTipoOrden                        "
              + "       ,idRecibo                           "
              + "       ,indicador                          "
              + "       ,idMedio                            "
              + "       ,SUM(vrMedio) AS vrMedio            "
              + "   FROM tblpagosmedios                     "
              + "   WHERE idLocal =                         "
              + "?1                             "
              + "   AND idTipoOrden = 9                     "
              + "   GROUP BY  idLocal                       "
              + "       ,idTipoOrden                        "
              + "       ,idRecibo                           "
              + "       ,indicador                          "
              + " 	  ,idMedio ) AS tmpMED                "
              + " ON tmpMED.idLocal =  tblpagos.idLocal     "
              + " AND tmpMED.idTipoOrden =                  "
              + "                      tblpagos.idTipoOrden "
              + " AND tmpMED.idRecibo = tblpagos.idRecibo   "
              + " AND tmpMED.indicador = tblpagos.indicador "
              + " INNER JOIN tblmediospago                  "
              + " ON tblmediospago.idMedio = tmpMED.idMedio "
              + " AND	tblmediospago.idLocal = tmpMED.idLocal "
              + " WHERE  tblpagos.idLocal   =        "
              + "?1                      "
              + " AND  tblpagos.idTipoOrden = 9      "
              + " AND (tblpagos.indicador            "
              + "               BETWEEN 1 AND 2)     "
              + " AND  tblpagos.idPeriodo   =        "
              + "?2                    "
              + " ORDER BY tmpMED.idMedio,           "
              + "          tblpagos.fechaPago,       "
              + "          tblpagos.idRecibo ", nativeQuery = true)
	  List<TblPagosDTO> listaRepRecaudoPeriodo(int idLocal, int idPeriodo);
	  
	  
	  
	  
	  @Query(value = " SELECT tblpagos.nitCC              "
              + "              AS idCliente,         "
              + " tblterceros.nombreTercero,         "
              + " tblpagos.idLocal,                  "
              + " tblpagos.idTipoOrden,              "
              + " tblpagos.idRecibo,                 "
              + " tblpagos.indicador,                "
              + " tblpagos.fechaPago,                "
              + " tmpMED.vrMedio AS vrPago,          "
              + " tblpagos.vrRteFuente,              "
              + " tblpagos.vrDescuento,              "
              + " tblpagos.vrRteIva,                 "
              + " tblpagos.idDcto,                   "
              + " tblpagos.idDctoNitCC,              "
              + " tblpagos.idPlanilla,               "
              + " tblpagos.vrRteIca,                 "
              + " tbltercerosruta.nombreCiclo        "
              + "                     + ' / ' +      "
              + " tbltercerosruta.nombreRuta         "
              + "                 AS nombreRuta,     "
              + " tblterceroestracto.nombreEstracto, "
              + " tblpagos.idPeriodo,                "
              + " ctrlusuarios.nombreUsuario         "
              + "                 AS aliasUsuario,   "
              + " tmpMED.idMedio,                    "
              + " tblmediospago.nombreMedio,         "
              + "        tblTerceros.CC_Nit           "
              + " FROM tblpagos                      "
              + " INNER JOIN tblterceros             "
              + " ON tblpagos.idLocal   =            "
              + "     tblterceros.idLocal            "
              + " AND tblpagos.nitCC    =            "
              + "   tblterceros.idCliente            "
              + " INNER JOIN tblterceroestracto      "
              + " ON tblterceros.idLocal     =       "
              + "    tblterceroestracto.idLocal      "
              + " AND tblterceros.idEstracto =       "
              + "   tblterceroestracto.idEstracto    "
              + " INNER JOIN tbltercerosruta         "
              + " ON tblterceros.idLocal     =       "
              + "         tbltercerosruta.idLocal    "
              + " AND tblterceros.idRuta     =       "
              + "          tbltercerosruta.idRuta    "
              + " INNER JOIN ctrlusuarios            "
              + " ON tblpagos.idLocal        =       "
              + "             ctrlusuarios.idLocal   "
              + " AND tblpagos.idUsuario     =       "
              + "           ctrlusuarios.idUsuario   "
              + " INNER JOIN			       "
              + " ( SELECT  idLocal                  "
              + "       ,idTipoOrden                 "
              + "       ,idRecibo                    "
              + "       ,indicador                   "
              + "       ,idMedio                     "
              + "       ,SUM(vrMedio)                "
              + " 	        AS vrMedio             "
              + "   FROM tblpagosmedios              "
              + "   WHERE idLocal =                  "
              + "?1                      "
              + "   AND idTipoOrden = 9              "
              + "   GROUP BY  idLocal                "
              + "       ,idTipoOrden                 "
              + "       ,idRecibo                    "
              + "       ,indicador                   "
              + " 	  ,idMedio ) AS tmpMED         "
              + " ON 	 tmpMED.idLocal     =          "
              + "          tblpagos.idLocal          "
              + " AND  tmpMED.idTipoOrden =          "
              + "      tblpagos.idTipoOrden          "
              + " AND  tmpMED.idRecibo    =          "
              + "         tblpagos.idRecibo          "
              + " AND  tmpMED.indicador   =          "
              + "         tblpagos.indicador	       "
              + " INNER JOIN tblmediospago           "
              + " ON 	tblmediospago.idMedio =        "
              + "         	tmpMED.idMedio	       "
              + " AND  tblmediospago.idLocal =       "
              + "         	tmpMED.idLocal	       "
              + " WHERE  tblpagos.idLocal   =        "
              + "?1                      "
              + " AND  tblpagos.idTipoOrden = 9      "
              + " AND (tblpagos.indicador            "
              + "               BETWEEN 1 AND 2)     "
              + " AND  tblpagos.idPeriodo   =        "
              + "?2                   "
              + "AND tbltercerosruta.idRuta =        "
              + "?3                       "
              + " ORDER BY tmpMED.idMedio,           "
              + "          tblpagos.fechaPago,       "
              + "          tblpagos.idRecibo ", nativeQuery = true)
	  List<TblPagosDTO> listaRepRecaudoPeriodoRuta(int idLocal, int idPeriodo, int idRuta);
	  
	  
	  
	  @Query(value = " SELECT tblpagos.nitCC              "
              + "              AS idCliente,         "
              + " tblterceros.nombreTercero,         "
              + " tblpagos.idLocal,                  "
              + " tblpagos.idTipoOrden,              "
              + " tblpagos.idRecibo,                 "
              + " tblpagos.indicador,                "
              + " tblpagos.fechaPago,                "
              + " tmpMED.vrMedio AS vrPago,          "
              + " tblpagos.vrRteFuente,              "
              + " tblpagos.vrDescuento,              "
              + " tblpagos.vrRteIva,                 "
              + " tblpagos.idDcto,                   "
              + " tblpagos.idDctoNitCC,              "
              + " tblpagos.idPlanilla,               "
              + " tblpagos.vrRteIca,                 "
              + " tbltercerosruta.nombreCiclo        "
              + "                     + ' / ' +      "
              + " tbltercerosruta.nombreRuta         "
              + "                 AS nombreRuta,     "
              + " tblterceroestracto.nombreEstracto, "
              + " tblpagos.idPeriodo,                "
              + " ctrlusuarios.nombreUsuario         "
              + "                 AS aliasUsuario,   "
              + " tmpMED.idMedio,                    "
              + " tblmediospago.nombreMedio,         "
              + "    tblTerceros.CC_Nit              "
              + " FROM tblpagos                      "
              + " INNER JOIN tblterceros             "
              + " ON tblpagos.idLocal   =            "
              + "     tblterceros.idLocal            "
              + " AND tblpagos.nitCC    =            "
              + "   tblterceros.idCliente            "
              + " INNER JOIN tblterceroestracto      "
              + " ON tblterceros.idLocal     =       "
              + "    tblterceroestracto.idLocal      "
              + " AND tblterceros.idEstracto =       "
              + "   tblterceroestracto.idEstracto    "
              + " INNER JOIN tbltercerosruta         "
              + " ON tblterceros.idLocal     =       "
              + "         tbltercerosruta.idLocal    "
              + " AND tblterceros.idRuta     =       "
              + "          tbltercerosruta.idRuta    "
              + " INNER JOIN ctrlusuarios            "
              + " ON tblpagos.idLocal        =       "
              + "             ctrlusuarios.idLocal   "
              + " AND tblpagos.idUsuario     =       "
              + "           ctrlusuarios.idUsuario   "
              + " INNER JOIN			       "
              + " ( SELECT  idLocal                  "
              + "       ,idTipoOrden                 "
              + "       ,idRecibo                    "
              + "       ,indicador                   "
              + "       ,idMedio                     "
              + "       ,SUM(vrMedio)                "
              + " 	        AS vrMedio             "
              + "   FROM tblpagosmedios              "
              + "   WHERE idLocal =                  "
              + "?1                      "
              + "   AND idTipoOrden = 9              "
              + "   GROUP BY  idLocal                "
              + "       ,idTipoOrden                 "
              + "       ,idRecibo                    "
              + "       ,indicador                   "
              + " 	  ,idMedio ) AS tmpMED         "
              + " ON 	 tmpMED.idLocal     =          "
              + "          tblpagos.idLocal          "
              + " AND  tmpMED.idTipoOrden =          "
              + "      tblpagos.idTipoOrden          "
              + " AND  tmpMED.idRecibo    =          "
              + "         tblpagos.idRecibo          "
              + " AND  tmpMED.indicador   =          "
              + "         tblpagos.indicador	       "
              + " INNER JOIN tblmediospago           "
              + " ON 	tblmediospago.idMedio =        "
              + "         	tmpMED.idMedio	       "
              + " AND  tblmediospago.idLocal =       "
              + "         	tmpMED.idLocal	       "
              + " WHERE  tblpagos.idLocal   =        "
              + "?1                      "
              + " AND  tblpagos.idTipoOrden = 9      "
              + " AND (tblpagos.indicador            "
              + "               BETWEEN 1 AND 2)     "
              + " AND  tblpagos.idPeriodo   =        "
              + "?2                    "
              + "AND tblpagos.fechaPago     =       "
              + "?3             "
              + " ORDER BY tmpMED.idMedio,           "
              + "          tblpagos.fechaPago,       "
              + "          tblpagos.idRecibo ", nativeQuery = true)
	  List<TblPagosDTO> listaRepRecaudoPeriodoFecha(int idLocal, int idPeriodo, String fecha);
	  
	  
	  
	  @Query(value = "SELECT tblpagos.idLocal,                    "
              + " 	   MAX(tblpagos.idPeriodo) AS idPeriodo,"
              + " 	   MAX(tblplus.idTipo) AS idTipo,       "
              + " 	   tblpagosmedios.IDPLU,                "
              + " 	   (tblcategorias.nombreCategoria+' '+  "
              + " 	   tblplus.nombrePlu) AS nombrePlu,     "
              + " 	   SUM(tblpagosmedios.vrMedio)          "
              + " 	                             AS vrMedio "
              + " FROM     tblpagos                           "
              + " INNER JOIN tblpagosmedios                   "
              + " ON tblpagos.idLocal =                       "
              + "                      tblpagosmedios.idLocal "
              + " AND tblpagos.idTipoOrden =                  "
              + "                  tblpagosmedios.idTipoOrden "
              + " AND tblpagos.idRecibo =                     "
              + "                     tblpagosmedios.idRecibo "
              + " AND tblpagos.indicador =                    "
              + "                    tblpagosmedios.indicador "
              + " INNER JOIN tblplus                          "
              + " ON tblplus.idLocal = tblpagosmedios.idLocal "
              + " AND tblplus.idPlu = tblpagosmedios.idPlu    "
              + " INNER JOIN tblcategorias                    "
              + " ON tblplus.idLocal = tblcategorias.idLocal  "
              + " AND tblplus.idLinea = tblcategorias.idLinea "
              + " AND tblplus.idCategoria =                   "
              + "                  tblcategorias.idCategoria  "                
              + " where tblpagos.idlocal =                    "
              + "?1                               "
              + " AND tblpagos.idTipoOrden IN (9,29)          "
              + " AND tblpagosmedios.vrMedio != 0             "
              + " AND tblpagos.idPeriodo =                    "
              + "?2                             "
              + " GROUP BY  tblpagos.idLocal,                 "
              + "           tblpagosmedios.IDPLU,             "
              + " 	      tblcategorias.nombreCategoria,    "
              + " 	      tblplus.nombrePlu", nativeQuery = true)
	  List<TblPagosDTO> listaRecuadoRubro(int idLocal, int idPeriodo);
	  
	  
	  @Query(value = "SELECT tblpagos.idLocal,                    "
              + " 	   MAX(tblpagos.idPeriodo) AS idPeriodo,"
              + " 	   MAX(tblplus.idTipo) AS idTipo,       "
              + " 	   tblpagosmedios.IDPLU,                "
              + " 	   (tblcategorias.nombreCategoria+' '+  "
              + " 	   tblplus.nombrePlu) AS nombrePlu,     "
              + " 	   SUM(tblpagosmedios.vrMedio)          "
              + " 	                             AS vrMedio "
              + " FROM     tblpagos                           "
              + " INNER JOIN tblpagosmedios                   "
              + " ON tblpagos.idLocal =                       "
              + "                      tblpagosmedios.idLocal "
              + " AND tblpagos.idTipoOrden =                  "
              + "                  tblpagosmedios.idTipoOrden "
              + " AND tblpagos.idRecibo =                     "
              + "                     tblpagosmedios.idRecibo "
              + " AND tblpagos.indicador =                    "
              + "                    tblpagosmedios.indicador "
              + " INNER JOIN tblplus                          "
              + " ON tblplus.idLocal = tblpagosmedios.idLocal "
              + " AND tblplus.idPlu = tblpagosmedios.idPlu    "
              + " INNER JOIN tblcategorias                    "
              + " ON tblplus.idLocal = tblcategorias.idLocal  "
              + " AND tblplus.idLinea =                       "
              + "                       tblcategorias.idLinea "                
              + " AND tblplus.idCategoria =                   "
              + "                  tblcategorias.idCategoria  "
              + " where tblpagos.idlocal =                    "
              + "?1                              "
              + " AND tblpagos.idTipoOrden IN (9,29)          "
              + " AND tblpagosmedios.vrMedio <> 0             "
              + " AND tblpagos.idPeriodo =                    "
              + "?2                             "
              + " AND tblpagos.fechaPago     =   ?3           "
              + " GROUP BY  tblpagos.idLocal,                 "
              + "           tblpagosmedios.IDPLU,             "
              + " 	      tblcategorias.nombreCategoria,    "
              + " 	      tblplus.nombrePlu", nativeQuery = true)
	  List<TblPagosDTO> listaRecuadoRubroFecha(int idLocal, int idPeriodo, String fecha);
	  
	  
	  @Query(value = "SELECT tbldctos.idLocal,                        "
              + "       tbldctos.idTipoOrden,                    "
              + "       tbldctos.idDcto,                         "
              + "       MAX(tbldctos.idCliente) AS  idCliente,   "
              + "       MAX(tmpTER.CC_Nit) AS nitCC,            "
              + "       MAX(tbldctos.nombreTercero) AS           "
              + "                              nombreTercero,    "
              + "       MAX(tmpTER.nombreRuta) AS nombreRuta,    "
              + "       MAX(tmpTER.nombreEstracto) AS            "
              + "                              nombreEstracto,   "
              + "       tblpagosmedios.idPlu,                    "
              + "       MAX(tblcategorias.nombreCategoria+' '+   "
              + "           tblplus.nombrePlu) AS nombrePlu,     "
              + "       (tblpagosmedios.vrMedio)   AS vrMedio   "
              + "FROM tblpagos                                   "
              + "INNER JOIN tblpagosmedios                       "
              + "ON tblpagos.idLocal = tblpagosmedios.idLocal    "
              + "AND tblpagos.idTipoOrden =                      "
              + "                 tblpagosmedios.idTipoOrden     "
              + "AND tblpagos.idRecibo = tblpagosmedios.idRecibo "
              + "AND tblpagos.indicador =                        "
              + "                       tblpagosmedios.indicador "
              + "INNER JOIN tblplus                              "
              + "ON tblplus.idLocal = tblpagosmedios.idLocal     "
              + "AND tblplus.idPlu = tblpagosmedios.idPlu        "
              + "INNER JOIN tblcategorias                        "
              + "ON tblplus.idLocal = tblcategorias.idLocal      "
              + "AND tblplus.idCategoria =                       "
              + "                      tblcategorias.idCategoria "
              + "INNER JOIN tbldctos                             "
              + "ON tbldctos.idLocal = tblpagos.IDLOCAL          "
              + "AND tbldctos.idtipoorden = tblpagos.idtipoorden "
              + "AND tbldctos.idCliente  = tblpagos.nitCC        "
              + "AND tbldctos.idPeriodo  = tblpagos.idPeriodo    "
              + "INNER JOIN                                      "
              + "    ( SELECT tblterceros.idLocal,               "
              + "             tblterceros.idCliente,             "
              + "             tblterceros.CC_Nit,                "
              + "             tblterceros.nombreTercero,         "
              + "             (tbltercerosruta.nombreCiclo+' '+  "
              + "             tbltercerosruta.nombreRuta)        "
              + "                                AS nombreRuta,  "
              + "             tblterceroestracto.nombreEstracto  "
              + "     FROM tblterceros                           "
              + "     INNER JOIN tbltercerosruta                 "
              + "     ON tblterceros.idLocal                     "
              + "                      = tbltercerosruta.idLocal "
              + "     AND tblterceros.idRuta                     "
              + "                      = tbltercerosruta.idRuta  "
              + "     INNER JOIN  tblterceroestracto             "
              + "     ON tblterceros.idLocal =                   "
              + "                   tblterceroestracto.idLocal   "
              + "     AND tblterceros.idEstracto =               "
              + "              tblterceroestracto.idEstracto )   "
              + "                               AS tmpTER        "
              + "     ON tmpTER.idCliente  = tbldctos.idCliente  "
              + "     AND tmpTER.idLocal   = tbldctos.idLocal    "
              + "     where tblpagos.idlocal =                   "
              + "?1                                  "
              + "AND   tblpagos.idTipoOrden  IN (9,29)           "
              + "     AND tblpagosmedios.vrMedio <> 0            "
              + "     AND tblpagos.idPeriodo =                   "
              + "?2                                "
              + "GROUP BY tbldctos.IDdcto,                       "
              + "         tblpagosmedios.IDPLU,                  "
              + "         tbldctos.idLocal,                      "
              + "         tbldctos.idTipoOrden,                  "
              + "         tblpagosmedios.vrMedio                 "
              + "ORDER BY tbldctos.idLocal,                      "
              + "         tbldctos.idtipoOrden,                  "
              + "         tbldctos.idDcto ", nativeQuery = true)
	  List<TblPagosDTO> listaDetalleRecaudo(int idLocal, int idPeriodo);
	  
	  
	  
	  @Query(value = " SELECT tblpagos.idLocal               "
              + "        ,tblpagos.idTipoOrden        "
              + "        ,tblpagos.idRecibo           "
              + "        ,tblpagos.fechaPago          "
              + "        ,tblpagos.vrPago             "
              + "        ,tblpagos.nitCC              "
              + "        ,tblterceros.nombreTercero AS nombreCliente   "
              + "        ,tblpagos.idUsuario          "
              + "        ,tblpagos.idPeriodo          "
              + "        ,tblpagos.idDcto             "
              + "        ,tblpagos.idDctoNitCC        "
              + "        ,tblpagos.idPlanilla         "
              + "        ,tblpagos.vrSaldo            "
              + "  ,tblterceroestracto.nombreEstracto "
              + "  FROM tblpagos                      "
              + "  INNER JOIN tblterceros             "
              + "  ON tblterceros.idLocal  =          "
              + "                 tblpagos.idLocal    "
              + "  AND tblterceros.idCliente  =       "
              + "                 tblpagos.nitCC      "
              + "  INNER JOIN tblterceroestracto      "
              + "  ON tblterceros.idLocal  =          "
              + "      tblterceroestracto.idLocal     "
              + "  AND tblterceros.idEstracto  =      "
              + "    tblterceroestracto.idEstracto    "
              + "  WHERE tblpagos.idLocal      =      "
              + "?1                       "
              + "  AND tblpagos.idTipoOrden    =      "
              + "?2                   "
              + "  AND tblpagos.idPeriodo      =      "
              + "?3                     "
              + "  ORDER BY fechaPago ", nativeQuery = true)
	  List<TblPagosDTO> listaAllRecaudo(int idLocal, int xIdTipoOrden, int idPeriodo);
	  
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = " DELETE FROM  tblpagos      "
              + " WHERE tblpagos.idLocal   = "
              + "?1             "
              + " AND tblpagos.idTipoOrden = ?2 ",
              nativeQuery = true)
	  public void retiraTemporal(int idLocal, int idTipoOrden);
	  
	  
	  @Query(value = "SELECT  tblpagos.idDcto     "
              + " FROM    tblpagos           "
              + " INNER JOIN  tbldctos       "
              + " ON tbldctos.IDLOCAL =      "
              + "          tblpagos.idLocal  "
              + " AND tbldctos.IDTIPOORDEN = "
              + "       tblpagos.idTipoOrden "
              + " AND tbldctos.idDcto =      "
              + "            tblpagos.idDcto "
              + " WHERE tblpagos.idLocal =   "
              + "?1             "
              + " AND tblpagos.idTipoOrden = "
              + "?2         "
              + " AND tblpagos.idDcto =      "
              + "?3              "
              + " AND tblpagos.idPeriodo = ?4  ", nativeQuery = true)
	  Integer validaDctoPago(int idLocal, int IdTipoOrden, int IdDcto, int idPeriodo);
	  
	  
	  
	  @Query(value = "SELECT MAX(tblpagos.idPlanilla)  "
              + "             AS maximoIdPlanilla "
              + "FROM tblpagos                    "
              + "WHERE tblpagos.idLocal       =   "
              + "?1                  "
              + "AND   tblpagos.idTipoOrden   = ?2  ", 
              nativeQuery = true)
	  Integer maximaPlanilla(int idLocal, int IdTipoOrden);
	  
	  
	  @Query(value = "SELECT MAX(tblpagos.idRecibo) "
              + "            AS maximoIdRecibo "
              + "FROM tblpagos                 "
              + "WHERE tblpagos.idLocal     =  "
              + "?1               "
              + "AND   tblpagos.idTipoOrden =  "
              + "?2          "
              + "AND   tblpagos.indicador   = ?3 ", 
              nativeQuery = true)
	  Integer maximoReciboIdLocalxIndicador(int idLocal, int IdTipoOrden, int indicador);
	  
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = "INSERT INTO tblpagos (idLocal,       "
              + "                      idTipoOrden,   "
              + "                      idRecibo,      "
              + "                      indicador,     "
              + "                      fechaPago,     "
              + "                      vrPago,        "
              + "                      nitCC,         "
              + "                      estado,        "
              + "                      idUsuario,     "
              + "                      vrRteFuente,   "
              + "                      vrDescuento,   "
              + "                      vrRteIva,      "
              + "                      vrRteIca,      "
              + "                      idPeriodo,     "
              + "                      idDcto,        "
              + "                      idDctoNitCC,   "
              + "                      idPlanilla,    "
              + "                      vrSaldo,       "
              + "                      idLog,         "
              + "                      idVendedor,    "
              + "                      idReciboCruce, "
              + "                      vrPagoCambio,  "
              + "                      comentario)    "
              + "VALUES (                             "
              + "?1, "
              + "?2, "
              + "?3, "
              + "?4, "
              + "?5, "
              + "?6, "
              + "?7, "
              + "?8, "
              + "?9, "
              + "?10, "
              + "?11, "
              + "?12, "
              + "?13, "
              + "?14, "
              + "?15, "
              + "?16, "
              + "?17, "
              + "?18, "
              + "?19, "
              + "?20, "
              + "?21, "
              + "?22,"
              + "?23)",
              nativeQuery = true)
	  public void ingresaPago(int idLocal, int idTipoOrden, int IdRecibo, int Indicador, String FechaPagoSqlServer, Double VrPago, int NitCC, int Estado, int IdUsuario,
			  				   Double VrRteFuente, Double VrDescuento, Double VrRteIva,  Double vrRteIca, int IdPeriodo, int IdDcto, int IdDctoNitCC, int IdPlanilla, Double VrSaldo,
			  				   int IdLog, int IdVendedor, int IdReciboCruce, Double VrPagoCambio, String Comentario);
	  
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = " DELETE FROM  tblpagos      "
              + " WHERE tblpagos.idLocal   = "
              + "?1             "
              + " AND tblpagos.idTipoOrden = ?2 "
              + " AND tblpagos.idLog = ?3 ",
              nativeQuery = true)
	  public void retiraPagosTemporales(int idLocal, int idTipoOrden, int idLog);
	  
	  
	  
	  @Query(value = "SELECT tblpagos.idLocal,        "
              + "       tblpagos.idTipoOrden,    "
              + "       tblpagos.idDcto,         "
              + "       tblpagos.idDctoNitCC,    "
              + "       tblpagos.indicador,      "
              + "       tblpagos.vrPago,         "
              + "       tblpagos.vrRteFuente,    "
              + "       tblpagos.vrDescuento,    "
              + "       tblpagos.vrRteIva,       "
              + "       tblpagos.vrRteIca,       "
              + "       tblpagos.nitCC,          "
              + "       tblpagos.idRecibo        "
              + "FROM   tblpagos                 "
              + "WHERE EXISTS (                  "
              + "SELECT tblpagosmedios.*         "
              + "FROM tblpagosmedios             "
              + "WHERE tblpagos.idLocal        = "
              + "        tblpagosmedios.idLocal  "
              + "AND tblpagos.idTipoOrden      = "
              + "    tblpagosmedios.idTipoOrden  "
              + "AND tblpagos.idRecibo         = "
              + "        tblpagosmedios.idRecibo "
              + "AND tblpagos.indicador        = "
              + "      tblpagosmedios.indicador) "
              + "AND tblpagos.idLocal          = "
              + "?1                 "
              + "AND   tblpagos.idTipoOrden    = "
              + "?2             "
              + "AND   tblpagos.idLog          = "
              + "?3                   "
              + "AND   (tblpagos.vrPago     != 0 "
              + "OR    tblpagos.vrRteFuente != 0 "
              + "OR    tblpagos.vrDescuento != 0 "
              + "OR    tblpagos.vrRteIva    != 0 "
              + "OR    tblpagos.vrRteIca    != 0)", nativeQuery = true)
	  List<TblPagosDTO> listaPagoProceso(int idLocal, int IdTipoOrden, int IdLog);
	  
	  
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = "INSERT INTO tblpagos         "
              + "           (idLocal          "
              + "           ,idTipoOrden      "
              + "           ,idRecibo         "
              + "           ,indicador        "
              + "           ,fechaPago        "
              + "           ,vrPago           "
              + "           ,nitCC            "
              + "           ,estado           "
              + "           ,idUsuario        "
              + "           ,vrRteFuente      "
              + "           ,vrDescuento      "
              + "           ,vrRteIva         "
              + "           ,vrRteIca         "
              + "           ,idPeriodo        "
              + "           ,idDcto           "
              + "           ,idDctoNitCC      "
              + "           ,idPlanilla       "
              + "           ,vrSaldo          "
              + "           ,idLog            "
              + "           ,idVendedor       "
              + "           ,idReciboCruce    "
              + "           ,vrPagoCambio)    "
              + "SELECT tblpagos.idLocal,                            "
              + "?1 AS idTipoOrden,                  "
              + "?2 AS idRecibo,                        "
              + "?3 AS indicador                       "
              + "      ,MIN(tblpagos.fechaPago) AS fechaPago,        "
              + "?4 AS vrPago                                "
              + "      ,MAX(tblpagos.nitCC) AS nitCC                 "
              + "      ,MIN(tblpagos.estado) AS estado               "
              + "      ,MIN(tblpagos.idUsuario) AS idUsuario         "
              + "      ,MIN(tblpagos.vrRteFuente) AS vrRteFuente     "
              + "      ,MIN(tblpagos.vrDescuento) AS vrDescuento     "
              + "      ,MIN(tblpagos.vrRteIva) AS vrRteIva           "
              + "      ,MIN(tblpagos.vrRteIca) AS vrRteIca,          "
              + "?5 AS idPeriodo,                   "
              + "?6 AS idDcto,                           "
              + "?7 AS idDctoNitCC,                 "
              + "?8 AS idPlanilla,                    "
              + "?9  AS vrSaldo                         "
              + " ,MAX(tblpagos.idLog) AS idLog,                     "
              + "?10 AS idVendedor                        "
              + "      ,MIN(tblpagos.idReciboCruce) AS idReciboCruce "
              + "      ,MIN(tblpagos.vrPagoCambio) AS vrPagoCambio   "
              + "FROM tblpagos                                       "
              + "WHERE tblpagos.idLocal     =                        "
              + "?11                                     "
              + "AND   tblpagos.idTipoOrden =                        "
              + "?12                                 "
              + "AND   tblpagos.idRecibo    =                        "
              + "?13                                    "
              + "AND   tblpagos.idLog       =                        "
              + "?14                                      "
              + "AND   tblpagos.idLog       =                        "
              + "?14                                       "                
              + "AND   tblpagos.vrPago      !=  0                    "
              + " GROUP BY tblpagos.idLocal,                         "
              + "      tblpagos.idTipoOrden,                         "
              + " 	 tblpagos.idRecibo,                            "      
              + " 	 tblpagos.indicador ",
              nativeQuery = true)
	  public void ingresaPagos(int xIdTipoOrdenNew, int xIdReciboNew, int xIndicadorNew,  Double VrPago, int xIdPeriodoActivo, int xIdDctoNew, String xIdDctoNitCCNew, int xIdPlanillaNew,
			  				   Double VrSaldo, int xIdVendedor, int idLocal,  int IdTipoOrden, int IdRecibo, int IdLog);
	  
	  
	  @Modifying
	  @Transactional
	  @Query(value = "DELETE FROM tblpagos        "
              + "WHERE tblpagos .idLocal   = "
              + "?1             "
              + "AND tblpagos .idTipoOrden = "
              + "?2        "
              + "AND tblpagos .indicador   = "
              + "?3           "
              + "AND tblpagos.idRecibo     =  ?4 ",
              nativeQuery = true)
	  public void retiraReciboTemporal(int idLocal, int idTipoOrden, int Indicador, int IdRecibo);
	  
	  
	  
	  
	  @Query(value = "SELECT tblpagos.idLocal,         "
              + "       tblpagos.idTipoOrden,     "
              + "       tblpagos.idRecibo,        "
              + "       tblpagos.indicador,       "
              + "       tblpagos.fechaPago,       "
              + "       tblpagos.vrPago,          "
              + "       tblpagos.nitCC,           "
              + "       tblpagos.estado,          "
              + "       tblpagos.idUsuario,       "
              + "       tblpagos.vrRteFuente,     "
              + "       tblpagos.vrDescuento,     "
              + "       tblpagos.idPeriodo,       "
              + "       tblpagos.vrRteIva,        "
              + "       tblpagos.vrRteIca,        "
              + "       tblpagos.idDcto,          "
              + "       tblpagos.idDctoNitCC,     "
              + "       tblpagos.idPlanilla,      "
              + "       tblpagos.vrSaldo,         "
              + "       tblterceros.nombreTercero "
              + "FROM   tblpagos                  "
              + "INNER JOIN tblterceros           "
              + "ON tblterceros.idCliente =       "
              + "                 tblpagos.nitCC  "
              + "AND tblterceros.idLocal =        "
              + "               tblpagos.idLocal  "
              + "WHERE EXISTS (                   "
              + "SELECT tblpagosmedios.*          "
              + "FROM tblpagosmedios              "
              + "WHERE tblpagos.idLocal      =    "
              + "        tblpagosmedios.idLocal   "
              + "AND tblpagos.idTipoOrden    =    "
              + "    tblpagosmedios.idTipoOrden   "
              + "AND tblpagos.idRecibo       =    "
              + "       tblpagosmedios.idRecibo   "
              + "AND tblpagos.indicador      =    "
              + "     tblpagosmedios.indicador    "
              + "AND tblpagos.idLocal     =       "
              + "?1)                 "
              + "AND  tblpagos.idLocal     =      "
              + "?1                  "
              + "AND    tblpagos.idTipoOrden =    "
              + "?2              "
              + "AND    tblpagos.idPlanilla  = ?3 ",
              nativeQuery = true)
	  List<TblPagosDTO> listaPlanilla(int idLocal, int IdTipoOrden, int IdPlanilla);
	  
	  
	  
	  
	  
	  
	  
	  
}
